name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  GITHUB_TOKEN:
    required: true
    description: 'input description here'
  child-pull-request-github-markdown-template:
    description: "bouh"
    required: false
    default: "- #{{ number }} @{{ author.login }}"
  github-markdown-template:
    description: "bouh"
    required: false
    default: "{{ childrenPullRequestMarkdowns.join(`\n`) }}"

  child-pull-request-output-markdown-template:
    description: "bouh"
    required: false
    default: "- [#{{ number }}]({{ url }}) {{ title }} @{{ author.login }}"
  output-markdown-template:
    description: "bouh"
    required: false
    default: "{{ childrenPullRequestMarkdowns.join(`\n`) }}"

  base-ref-name-filter:
    required: false
    description: 'Keep only the children pull requests targeting this branch name'

runs:
  using: 'node16'
  main: 'dist/index.js'
