name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  GITHUB_TOKEN:
    required: true
    description: 'input description here'
  pull-request-description-template:
    description: "bouh"
    required: false
    default: "- #{{ number }} @{{ author.login }}\\n"
  base-ref-name-filter:
    required: false
    description: 'Keep only the children pull requests targeting this branch name'

runs:
  using: 'node16'
  main: 'dist/index.js'
